node-config/node-config

lib/config.js
package.json
test/2-config-test.js
test/config/default.hjson

I've added support for Hjson, a configuration file format that's similar to JSON but with a simplified syntax.
It supports #, // and /**/ style comments as well as avoiding trailing/missing comma and other mistakes. For details and syntax see http://laktak.github.io/hjson/

Hjson Support

---

lib/config.js
test/6-strict-mode.js

Note that the following wiki page will also need to be updated: https://github.com/lorenwest/node-config/wiki/Strict-Mode
Of course, since many people will still have the old version and will Google the text of the error message, you may want to include both versions of the text in that wiki so they continue to find the answer.

Fixes an error message that was missing a word

---

lib/config.js

...x issues with using the project in windows

Used Path.Join to concantenate folder location strings. This fix will fix issues using the project in windows

---

lib/config.js

As mentioned in pull-request https://github.com/lorenwest/node-config/pull/213 this pull request refactors parseFile and extracts string-based format parsing to a second function. Only .js, .coffee and .iced remains in parseFile.
This is needed for a later use.

Refactor: split up parseFile into a second function parseString for string-only based formats

---

lib/config.js
test/2-config-test.js
test/config/default.json

This arose becasue of the way comments are stripped from JSON. As comments will remain supported in node-config (#256) this change will correctly handle parsing JSON strings regardless of whether or not a comment is encountered.

Correctly handle parsing of inline JSON

---

lib/config.js

So it turns out the problem in #258 wasn't so much inline JSON as JSON with empty strings. This _should_ fix those problems, but again all regex based solutions are going to have corner cases.
Fixes #259

Fix nested quotes with support for empty strings

---

lib/config.js
package.json
test/config/custom-environment-variables.json

This appears to have been added in #1 but it actually causes problems with the module due to the way the data is mutated with regular expressions.
I would like to have this removed because:
1. Comments in straight JSON are not valid according to the spec
2. node-config already supports JSON5, so if comments are required users can use that file format instead.
The case where this breaks is when a JSON file has all of its whitespace removed, for example, consider this original config file:
```json
{
"version": "v3.1",
"supportedVersions": [
"v3",
"v3.1"
],
"supportedExt": [
"bulk"
],
"publicRoot": "http://localhost:3000",
"port": 3000,
"processes": 0,
"killTimeout": 10000,
"api": {
"host": "",
"options": {}
},
"redis": {
"host": "127.0.0.1",
"options": {}
}
}
```
Now suppose we remove …

More robust handling of JSON

---

lib/config.js

Before, we used the `for..in..` construction to iterate over object
properties, which returns the keys in an arbitrary order which is
usually-but-not-always the key insertion order.
Now object keys are traversed in the order returned by calling sort() on
the key names
Having a predictable resolution order could be useful if you want one
defered value to refer to another defered value. Now one should reliably
resolve before the other.
The change passes all the regression tests. No new test coverage was added. Due to the nature, it was unclear how to test the case of the resolution order being unpredictable in different JavaScript environments.
It's possible that the change could cause someone's code somewhere to break, if they were depending on the old, arbitrary resolution order, which …

Resolve defered values in predictable order for consistent results. Fixes #265

---

lib/config.js
test/2-config-test.js
test/config/default.yaml

With Yaml, an empty subobject becomes `null`, and `typeof null` is `object` which makes getImpl descend into it.
Test fails without config.js change and passes with.

Handle null subobject case

---

lib/config.js

Fix to catch the JSON parse exceptions which have changed in Node v6.
Position info has been appended to the end of the message, so it now looks like "Unexpected token / in JSON at position X"

Handle node v6 SyntaxError message containing position data

---

lib/config.js
test/1-protected-test.js

In 1.20.1 extendDeep would some things including methods on the prototype (e.g. has).  With 1.20.2 that when __lookupGetter__ was removed.  The fix in 1.20.3 didn't fix that although it did guard against the cases when getPropertyDescriptor returned undefined.  This change restores the current code structure where if what is being copied isn't one of the known types (including property descriptor) then it is simply copied.  This change also creates a test for this case.  This test passes in 1.20.1, not in 1.20.2/3, and then again after change is applied.

Fix prototype merge

---

lib/config.js
test/5-config/default.js
test/util.js

Example use case: load module defaults which you then merge with util.setModuleDefaults
```jsx
import config from 'config'
const ourConfigDir = path.join(__dirname, 'config')
const baseConfig = config.util.loadFileConfigs(ourConfigDir)
config.util.setModuleDefaults('MyModule', baseConfig)
```
See #276

util.loadFileConfigs: support optional source dir

---

defer.js
lib/config.js
test/3-config/default.js
test/3-config/local.js
test/3-deferred-configs.js

I would like to suggest this PR to extend functionality for deferredConfigs. This PR is fully backward compatible.
When merging a config file which has deferred values the value from the previous file is saved into the DeferredConfig object. Later when deferred values are resolved this saved value is passed to the resolver function.
I am currently developing a deferred resolver which allows me to load values from etcd – hopefully I will be able to release this in the next week. Yes, it is synchronously but this is ok in my context. When no value is in etcd I wanted to get the last one so I did this little change.
Maybe some other people are in need of this? :)
Here is an example:
```yaml
someValue: default
```
```js
// local.js
module.exports = {
someValue: defer(function (cfg, …
```

original/previous value for deferredConfig

---

lib/config.js

Some IDEs and other tools incorrectly state that argument of type `String` is not assignable to param of type `STRING`. This fixes those sort of issues.

Update config.js with correctly cased type def.

---

lib/config.js
package.json
test/1-protected-test.js
test/10-gitcrypt-test.js
test/2-config-test.js
test/4-array-merging.js
test/5-getConfigSources.js
test/6-strict-mode.js
test/7-unicode-situations.js
test/8-config-extending.js
test/9-raw-configs.js
test/_utils/isSupportedVersion.js
test/_utils/requireUncached.js
test/x-config-test-ts.js
test/x-config-ts/default.ts
test/x-config-ts/local.ts
test/x-config-ts/types.ts
test/x-deferred-configs-ts.js

This branch is adding TypeScript support by adding `*.ts` extensions handling with `ts-node` programmatic API.
Deferred config test is prefixed with `x-*` because when running multiple tests in parallel, `ts-node` is trying to parse multiple files with same name, putting them to same directory without prefixing etc. With `x/y/z` prefixing we are sure that this test will run as last and we won't see such error messages:
> Unable to compile TypeScript
> Cannot write file '/Library/WebServer/Documents/node-config/$$ts-node$$/test/config/default.js' because it would be overwritten by multiple input files.
Lazy loading of `ts-node` module is enabled by default and `allowJs` is set to true because we need to be able to require `defer.js` in example.

Resolve #366 - Add TypeScript support

---

test/1-protected-test.js

The result from extendDeep was never verified to be the same as the
expected value. This is informative of the behaviour of extendDeep since
there are only two tests that extend with more than one object and
neither of them verified the result before.

extendDeep test improvements

---

.travis.yml
package.json

As per https://github.com/lorenwest/node-config/pull/428#issuecomment-321730793, this PR will remove non-supported nodejs versions (0.8, 0.10, 0.12); and add support for v7, v8 for travisci.

update supported nodejs platforms

---

.travis.yml

This MR will enable travis ci to run the node-config test cases on the nodejs 9 runtime which was released Nov 1.
I've run the test cases locally using node v9.1.0 locally; all 206 cases passed successfully.

add nodejs9 to travisci

---

lib/config.js
test/13-node_env-hostname.js

Hi,
We are facing some issues in some distros that do not have HOSTNAME (or HOST) environment variable setted. In this case, we are receiving `undefined` result when trying to `config.util.getEnv('HOSTNAME')`.
This PR is a suggestion to try to do what says in the comments (lib/config.js:662)
> Determine the host name from the OS module, $HOST, or $HOSTNAME

Fixed 'hostname' value selection when there is no environment variable for that

---

lib/config.js

Fixes #437.
node-config should not register ts-node in case there is already .ts extension handler.

Fixes #437 (ts-node double registration)

---

lib/config.js
test/9-config/default.js
test/9-raw-configs.js

Moving the `raw` wrapped object unwrapping into `makeImmutable`
is piggy-backing on the existing recursive object graph traversal
to ensure that regardless of how deep a raw-wrapped object is
within the configuration, it will be unwrapped.
The ordering of `makeImmutable` and `getImpl` was flipped in order
to consistently return an immutable config. Previously, a mutable
configuration was returned on first `get()`, and an immutable one
on subsequent `get()`s.
Fixes lorenwest/node-config#467

Support for nested raw() in javascript configurations

---

lib/config.js
test/2-config-test.js
test/config/default.js

When immutable is called upon a config, this change freezes any arrays found. If there is an attempt to push a value onto the array, a TypeError is thrown.
I'm not sure if this is a desired approach for this library, as most attempted modifications to immutable keys are silently ignored by default. Throwing an error seems a bit harsh... Open to suggestions.

Immutable arrays

---

.gitignore
lib/config.js
test/2-config-test.js

Merge request for:
https://github.com/lorenwest/node-config/issues/505
These changes ensure config properties of type array and their child objects are made immutable recursively, and prevent adding new properties to objects.
The following test is broken:
"Prototypes are applied by setModuleDefaults even if no previous config exists for the module"
due to the fact that setModuleDefaults will update the config object with default values, which in some use cases will add new properties.
I think this conflicts with the config object being immutable, but not sure how setModuleDefaults should behave -> should this method create non immutable copies of config values, merge them with defaults and then make them immutable (if ALLOW_CONFIG_MUTATIONS === false)?
@markstos  @lorenwest

Ensure config array items and objects are sealed.

---

lib/config.js
test/2-config-test.js

* Remove unnecessary line causing the bug.
* Added a new regression test for this.
* Existing tests still pass.
Fix for #518.

Don't extend the input module config with its own key

---

lib/config.js
test/9-config/default.js
test/9-raw-configs.js

Very little changes in code, validate a promise using `util.isObject(obj) && obj.toString() === '[object Promise]'`.
What do you think?

Fixed #449 - support native promises by default, no need to wrap them in raw

---

defer.js
lib/config.js
package.json
test/3-config/default.js
test/3-config/local.js
test/3-deferred-configs.js

@markstos This is my suggested solution for fixing #266 aka the double-defer bug **using getters**.
~~Notice that it does add a dependency to support synchronous-promises which prevent the library becoming accessible before all deferred configs has been resolved.~~
Let me know what you think..

Fixed double-defer bug #266

---

lib/config.js
parser.js
test/16-config/default.custom
test/16-config/default.json
test/16-config/default.json5
test/16-config/default.yaml
test/16-config/local.custom
test/16-config/local.yml
test/16-config/parser/custom-1.js
test/16-config/parser/custom-2.js
test/16-config/parser/custom-3.js
test/16-custom-parser.js

This is my initial proposal. 
I just wanna make sure you're okay with this change before moving forward and adding a new env-var which will be loaded and merged with `util.parsers` before loading configuration files.
The only change to logic offered here is the addition of `util.setParser` and `util.removeParser`. 
Everything else should continue working in exactly the same ways as before.
Note: There's a typo in the commit message. Refers to #181

#181 - Support custom Parsers definitions from an external source

---

async.js
test/15-async-configs.js
test/15-config/default.js
test/15-config/local.js

I took the liberty to extend my former solution and added support for both promises and async functions.
If we only allow promises and a user will want to override one promise with another, then although the value will be correct the code for both promises would execute, which isn't optimal.
By allowing `asyncConfig` to receive an async function (a function which return a promise) we solve this problem with the same logic used for the `deferConfig`. 
So now if we detect a function we wrap it with `asyncConfig` and pass it to `deferConfig` to handle its initialization. `deferConfig` will execute the function which will return an `AsyncConfig` instance containing the resulted promise, later to be handled by `resolveAsyncConfigs`.
Issue: https://github.com/lorenwest/node-config/issues/186 …

Add async configuration support - asyncConfig

---

async.js
lib/config.js
test/15-async-configs.js
test/15-config/local.js
test/2-config-test.js
test/x-config/default.xml
test/x-config/local.yml

Addresses #560
1. Improved logic to first read directory files and filter those which are relevant to us, then we only try to read them.
2. Allow passing `CONFIG_DIR` with multiple directories separated by `:`. (like PATH)
3. Make sure `NODE_APP_INSTANCE` is loaded on all supported extensions.
Notice that current resolution order won't be separated to each directory but according to files resolution rules. The directory is only used to sort between exact files in separate directories, then the directory index in `CONFIG_DIR` is used to sort.
```
util.locateMatchingFiles('a:b', {'default': 1, 'local': 2})
a/default
b/default
a/local
b/local
```
What do you think  the logic should be in case we add support for multiple directories?
**Edit** I believe the ideal use case would look like that: …

#560 Improve performance + Support multiple config directories + Fix #512

---

async.js
lib/config.js
test/15-async-configs.js
test/15-config/local.js

Now every async function used by `asyncConfig` is also deferred, which means you can access the resolved config including other asyncConfig promises (or native ones), and dependencies are automatically resolved.
Example:
```
async function dbConfig() {
// services information and required secrets
}
async function userToken(cfg) {
const { username, secretKey } = await cfg.dbConfig;
return await fetchToken(username, secretKey);
}
module.exports = {
dbConfig: asyncConfig(dbConfig),
userToken: asyncConfig(userToken),
};
```

Improved asyncConfig to support new deferConfig mechanism

---

lib/config.js

I didn't add tests because we don't run tests on Windows servers as part of our CI.

Fix #567 - Missing path.delimiter breaks windows absolute paths

---

lib/config.js
test/5-config/custom-environment-variables.json
test/5-extra-config/custom-environment-variables.json
test/5-getConfigSources.js

When working with multiple config dirs, custom-environment-variables files no longer works. 
The `getCustomEnvVars` method tries to create file paths by concatenating `CONFIG_DIR` with optional file names, but `CONFIG_DIR` can be a string with multiple dir paths, separated by `:`.

Fixed issue with getCustomEnvVars method and multiple config dirs

---

lib/config.js
test/config/default.js

Simple code replicating issue:
`config/default.js`
```javascript
module.exports = {foo: Buffer.from('bar', 'ascii'), bar: 5};
```
`index.js`
```js
require('config').get('bar')
```

Fixed issue with Buffers in config throwing error in util.makeImmutable

---

parser.js
test/2-config-test.js
test/config/custom-environment-variables.json

- Added support to parse boolean and nimeric config values
- Added supporting tests
This PR might resolve Issue: #615, #589

Parse boolean and numeric config passed from environment variables

---

lib/config.js
test/6-strict-mode.js

Fix for #460 .
Would love your feedback 🙂

FIX #460 - Strict mode warning refer to appropriate env variable

---

async.js
lib/config.js
test/17-config/default.toml
test/17-toml.js

The TOML library clears the object prototype which results in foo.hasOwnProperty(bar) failing.
Using Object.hasOwnProperty.call(foo, bar) instead.
Fix #574

Fix #574: TOML error when using array of tables

---

package.json

Subdomains of github.com are deprecated for GitHub Pages and not redirecting anymore to github.io since April 15, 2021.

Fix homepage url

---

lib/config.js
test/1-protected-test.js
test/19-config/custom-environment-variables.json
test/19-config/default.js
test/19-custom-environment-variables.js
test/2-config-test.js

This is a first-attempt PR to add tests to demonstrate the problem described in #593, and to fix that issue. It keeps the behavior that allows other falsey values, such as numeric `0`, which was a main benefit of the PR (#582) that stopped ignoring empty environment variables.
Note that I had to adjust a couple existing tests that broke due to my fix; I believe the tests were describing behavior that is incompatible with ignoring empty strings, and both tests were added at the same time or after the old behavior was broken in 3.3.0. Please let me know if this is incorrect or undesired.
Also note that I am unfamiliar with the test format that `node-config` uses, so I'd be happy to reformat/reorganize my added tests if there's a better place to put them - just let me know.

Fix #593 (Don't treat empty strings as valid values)

---

lib/config.js

This change removes all of the unused variables and fixes one case of variable shadowing.
I am slowly working toward separating config.util into its own file, but there are a number of couplings between it and the parent scope that will need to be sorted out.

Cleanup of file scoped environment variables

---

lib/config.js
test/20-config/default.js
test/20-extra-config/default.js
test/20-multiple-config.js

- Add tests for the multiple configurations feature
- transform each relative config dir to an absolute path
fix: https://github.com/lorenwest/node-config/issues/660

Allow multiple relative directory paths separated by path.delimiter to work

---

lib/config.js
test/21-reentrant/default.js
test/21-reentrant/nested/default.js
test/21-reentrant/runtime.json
test/util.js

Multiple or nested calls to loadFileConfigs can result in file-scoped variables in lib/config.js being overwritten before being used.
CONFIG_DIR is especially problematic, but I also fixed runtime.json support because it represents the last use of CONFIG_DIR, after parseFiles() has been called.

Reentrancy bugs

---

parser.js
test/x-config-js-test-transpiled.js
test/x-config-js-transpiled/default.js
test/x-config-js-transpiled/local.js

This pull request aims to finish previously opened pull request #566. Adding support for transpiled JS modules (those with `module.exports = config`) is helpful when you have a `config` directory inside your `src` directory in the `TypeScript` project.
To ensure that the file is transpiled and to preserve backward compatibility, I have added a check for `__esModule` and the `default` property that it is an object.

Support loading transpiled JS config files

---

package.json

json5 dependency is vulnerable in the current version which is `2.2.1`, this PR contains the fix. The vulnerability is resolved in version  `2.2.2`.
This PR resolves the issue #712

fix(vulnerability): upgrade json5 version from 2.2.1 to 2.2.2

---

lib/config.js

Hi there!
Comparing `typeof xxx === 'undefined'` is safer than using `xxx === undefined` because `undefined` is a global variable that can be overwritten.

refactor: 💡 xxx === undefined => typeof xxx === 'undefined'

---

parser.js

This PR addresses https://github.com/node-config/node-config/issues/530 and https://github.com/node-config/node-config/issues/613
The problem was that newly registered `ts-node` took over transpilation of all files.
Using `ignore` option we can exclude transpiling again anything that is not a typescript file.
First regex `(?:^|/)node_modules/` is just the default that is used by `ts-node` to exclude `node_modules` if `ignore` option is unspecified.

Fix source maps when using ts config files, improve performance loading ts config files

---

lib/config.js
parser.js
test/9-config/default.js

This addresses issues mentioned in #715 
The issue mentioned in #704 will be investigated further

fix: lack of comments removal, invalid regexp

---

parser.js

fix https://github.com/node-config/node-config/issues/755

fix: webpack bundling compatibility

---

lib/config.js
parser.js

Fixes the following warnings when run in Node@22
```
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:20281) [DEP0053] DeprecationWarning: The `util.isObject` API is deprecated. Please use `arg !== null && typeof arg === "object"` instead.
(node:20281) [DEP0044] DeprecationWarning: The `util.isArray` API is deprecated. Please use `Array.isArray()` instead.
(node:20281) [DEP0055] DeprecationWarning: The `util.isRegExp` API is deprecated. Please use `arg instanceof RegExp` instead.
(node:20281) [DEP0047] DeprecationWarning: The `util.isDate` API is deprecated.  Please use `arg instanceof Date` instead.

Remove usage of deprecated utils to fix warnings in Node 22

---

.github/workflows/tests.yml
package.json

I done did forgot to add `runs-on`, so the PR CI is currently invalid, and won't run.

fix: add runs-on to pr ci tests

---

lib/config.js
package.json
test/11-regexp.js
test/21-date.js
test/22-binary.js
test/23-serialize.js
test/23-serialize/default.js
test/config/default.js
test/config/local-3.yml

* Adds `get` trap in `util.makeImmutable`s `Proxy` config
* Removes `instanceof` checking
* Fixes https://github.com/node-config/node-config/issues/761
* Add tests to confirm immutability
* Adds a `vows` script so that individual test files can be run
* Adds test to assert serialization with `JSON.stringify`

feat: add `get` trap to Proxy for agnostic prototype access

---

lib/config.js
test/22-config/default-instance.json
test/22-config/default-instance.yml
test/22-config/default.yml
test/22-files-order.js

This will fix the loading order when having different file extensions and working with APP_INSTANCE as well.
Instead of doing a `forEach` on basenames and extensions, then adding the `APP_INSTANCE`, the filename using the `APP_INSTANCE` is defined before going through all extensions, so that it is loaded after all extensions without the APP_INSTANCE being defined.
Did a console.log (that I removed) for the `allowedFiles` object when running the added test to show the difference:
Before the fix:
After the fix:

Fix GH-746 - Loading config files order with APP_INSTANCE

---

.gitignore
.npmignore
package.json

With the prospect of adding additional maintainers, before other people start merging PRs it would be good to have a clearer picture of what we have and that includes code coverage data on the builds. 
nyc@15.1.0 is the most recent version of nyc that is compatible with node >= 10, and I would rather not open engines discussion at this time.

Add nyc for code coverage

---

async.js
lib/config.js

for-in will iterate on Strings.
Fixes #610
Adding a sanity check to avoid recursing on them, which should speed up both of these operations substantially.
Also swapping Object.keys() in since we end up filtering by hasOwnProperty() anyway.

Fix over-recursion in async and deferred processing

---

lib/config.js

Since none of the code uses more than 3 arguments this doesn't really affect performance much (tested with tinybench) Using arguments deoptimizes JS code, but it's the only spot we're doing this, so it should go.
Spotted while looking at the traversal bug.

Replace arguments fiddling with spread operator.

---

lib/config.js
parser.js
test/2-config-test.js
test/config/default.jsonc

While **node-config** DO support comments in `.json` and `.json5` file extensions (it uses **json5** parser for both), it doesn't support the `.jsonc` file extension.
Why is this important? Comments are not allowed in the **JSON** specification, and even if they are supported by **node-config**, adding them to a `.json` file will trigger all sorts of errors in IDEs, linters, formatters, code analysis tools, and alike.
Using `.json5` file extension could be a solution, if you're willing to open the doors of your config files to a completely new and full of possibilities file format (**JSON5**). However, if you just want the good ol' **JSON** format, with comments, `.jsonc` is what you need

Add support for jsonc file extension

---

lib/config.js
lib/util.js
test/2-config-test.js

This code always did more work than it needed to but during the config.js/util.js split it sprouted a couple more defensive copies.
The existing code has some unnecessary tree merge logic in util.js, which makes the code difficult to follow. This change simplifies that code.
Within Config.util however, that 'unnecessary' logic does create one feature which my previous PR did not cover: Calling Config.get() prior to calling `setModuleDefaults` in 4.0 and earlier resulted in the Config object still being able to see the new defaults. That can only happen when allow_config_mutations is true, but this PR conserves that behavior when it is necessary.

Simplify the merge logic in setModuleDefaults(), fix regression on trunk.

---

lib/config.js
test/makeImmutable-shared-refs.js

Under certain circumstances in a config with a shared reference,
makeImmutable could end up being called twice on the same property,
throwing an error.
As a fix, we check if a property is already immutable, and if so, move on.
- Added test coverage, confirming that the the test failed before the patch and passes after it.

BugFix: shared references could trigger "Cannot redefine property"

---

test/0-util.js
test/8-config-extending.js
test/config/default.cson

Quite a few of our tests for util.js rely on being called via the Config.util tests.  Since most of those methods are now deprecated, they need their own testing in place prior to deleting the old functions as part of work toward #569 which is already underway.

Increase direct testing of util.js

---

lib/config.js
lib/util.js
test/0-util.js
test/19-custom-environment-variables.js

This finishes most of the extraction work of code exposed in Config.util that has been earmarked for removal for the last few years.
These changes are sufficient to support some setModuleDefaults() patterns I've encountered, and writing CI/CD support tools for projects that use node-config in fairly heavy rotation.
This also covers some of the bullet points in #569

Extract more of Config.util to util.js

---

test/0-util.js

Fix tests from a branch that missed out on a class rename.

'LoadInfo' tests from another PR did not get renamed in the main PR

---

lib/util.js
test/0-util.js

This fixes:
- #687 
- #822
- #827

Segregate defaults data from config data, so deferreds and multiple setModuleDefaults calls can be applied properly.

---

package.json

c8 is compatible with nyc but uses nodejs' internal tooling for code coverage. 
One of the consequences of switching to this is that we no longer need to filter out the .ts tests from coverage, as it seems not to interact with require.extensions.

Switch to c8 for code coverage.
